Repository DeveloperAcademy-POSTECH/MacC-GetARock, pull requests merged in 2022-11, with the labels that each got.

#17 [Setting] Auto-Assigner를 통해 reviewer를 자동 할당합니다.
  .github/auto_assign.yml
Labels: 🎸 알로라, Setting

#19 [Setting] 현재 프로젝트에 Pull request template를 추가합니다.
  .github/PULL_REQUEST_TEMPLATE.md.md
Labels: 🎸 알로라, Setting

#34 [Chore] 서비스가 다크 모드만 지원하도록 변경했습니다.
  GetARock/GetARock.xcodeproj/project.pbxproj
  GetARock/GetARock/Global/Supports/Info.plist
Labels: 🎸 알로라, Setting

#41 [Design] 밴드 정보 영역의 레이아웃을 구현했습니다.
  GetARock/GetARock.xcodeproj/project.pbxproj
  GetARock/GetARock/Global/Resource/Storyboards/BandInfo.storyboard
  GetARock/GetARock/Screen/BandInfo/BandInfoViewController.swift
Labels: 🎸 이브, Design

#43 [Add] 어플에서 사용하는 UIColor Extension을 제작했습니다.
  GetARock/GetARock.xcodeproj/project.pbxproj
  GetARock/GetARock/Global/Extension/UIColor+Extension.swift
  GetARock/GetARock/Global/Utils/UIView+Gradation.swift
Labels: 🎸 노엘, Add

#46 [Design] 주변의 이벤트와 밴드 정보를 확인할 수 있는 지도 뷰 UI를 구성합니다.
  GetARock/GetARock.xcodeproj/project.pbxproj
  GetARock/GetARock/Global/Resource/Assets.xcassets/BandLocation.imageset/BandLocation.svg
  GetARock/GetARock/Global/Resource/Assets.xcassets/BandLocation.imageset/Contents.json
  GetARock/GetARock/Global/Resource/Assets.xcassets/CreateEvent.imageset/Contents.json
  GetARock/GetARock/Global/Resource/Assets.xcassets/CreateEvent.imageset/makeEvent.svg
  GetARock/GetARock/Global/Resource/Assets.xcassets/CurrentLocation.imageset/Contents.json
  GetARock/GetARock/Global/Resource/Assets.xcassets/CurrentLocation.imageset/CurrentLocation.svg
  GetARock/GetARock/Global/Resource/Assets.xcassets/GatheringLocation.imageset/Contents.json
  GetARock/GetARock/Global/Resource/Assets.xcassets/GatheringLocation.imageset/GatheringLocation.svg
  GetARock/GetARock/Global/Resource/Assets.xcassets/MyEvent.imageset/Contents.json
  GetARock/GetARock/Global/Resource/Assets.xcassets/MyEvent.imageset/MyEvent.svg
  GetARock/GetARock/Global/Resource/Assets.xcassets/MyPage.imageset/Contents.json
  GetARock/GetARock/Global/Resource/Assets.xcassets/MyPage.imageset/MyPage.svg
  GetARock/GetARock/Global/Resource/Assets.xcassets/Setting.imageset/Contents.json
  GetARock/GetARock/Global/Resource/Assets.xcassets/Setting.imageset/Setting.svg
  GetARock/GetARock/Global/Resource/Storyboards/MainMap.storyboard
  GetARock/GetARock/Screen/MainMap/MainMapViewController.swift
Labels: 🎸 알로라, Design

#49 [Add] 주요 데이터를 모델링했습니다.
  GetARock/GetARock.xcodeproj/project.pbxproj
  GetARock/GetARock/Global/Utils/UIView+Gradation.swift
  GetARock/GetARock/Network/Model/AgeGroup.swift
  GetARock/GetARock/Network/Model/Band.swift
  GetARock/GetARock/Network/Model/Coordinate.swift
  GetARock/GetARock/Network/Model/Gathering.swift
  GetARock/GetARock/Network/Model/GatheringComment.swift
  GetARock/GetARock/Network/Model/Location.swift
  GetARock/GetARock/Network/Model/PlayPosition.swift
  GetARock/GetARock/Network/Model/VisitorComment.swift
Labels: 🎸 스누피

#55 [Design] 내 모여락 리스트 화면 UI를 구현합니다.
  GetARock/GetARock.xcodeproj/project.pbxproj
  GetARock/GetARock/Global/Resource/Storyboards/GatheringView.storyboard
  GetARock/GetARock/Global/Resource/Xibs/GatheringCell.xib
  GetARock/GetARock/Screen/Gathering/GatheringCell.swift
  GetARock/GetARock/Screen/Gathering/GatheringCreatedViewController.swift
Labels: 🎸 태니, Design, 내 모여락

#53 [Design] 각 화면으로 전환되는 커스텀 버튼 클래스를 구현합니다.
  GetARock/GetARock.xcodeproj/project.pbxproj
  GetARock/GetARock/Global/UIComponent/ViewSwitchedSegmentedControl.swift
Labels: 🎸 머피, Design

#69 [Refactor] UIColor extension 코드 수정 #67
  GetARock/GetARock/Global/Extension/UIColor+Extension.swift
  GetARock/GetARock/Global/Utils/UIView+Gradation.swift
Labels: 🎸 노엘, Refactor

#61 [Design] 모여락(밴드 이벤트) 추가 화면을 구현합니다.
  GetARock/GetARock.xcodeproj/project.pbxproj
  GetARock/GetARock/Global/Resource/Storyboards/AddGathering.storyboard
  GetARock/GetARock/Screen/AddGathering/AddGatheringViewController.swift
Labels: 🎸 유니스, Design, 모여락 추가

#72 [Hotfix] 컬러 익스텐션 업데이트에 코드의 컬러를 업데이트합니다.
  GetARock/GetARock/Global/UIComponent/ViewSwitchedSegmentedControl.swift
Labels: !HOTFIX

#59 [Design] 밴드 멤버 영역을 Collection View로 구현합니다.
  GetARock/GetARock.xcodeproj/project.pbxproj
  GetARock/GetARock/Global/Resource/Storyboards/BandInfo.storyboard
  GetARock/GetARock/Screen/BandInfo/BandInfoViewController.swift
  GetARock/GetARock/Screen/BandInfo/Cell/BandMemberCollectionViewCell.swift
  GetARock/GetARock/Screen/BandInfo/VC/BandInfoViewController.swift
Labels: 🎸 이브, Design

#80 [Design] 밴드상세화면의 상단뷰를 구현합니다
  GetARock/GetARock.xcodeproj/project.pbxproj
  GetARock/GetARock/Screen/BandInfo/TopViewOfInfoView.swift
  GetARock/GetARock/Screen/BandInfo/VC/BandPageViewController.swift
Labels: 🎸 머피, Design, 밴드 상세

#76 [Add] 더미 데이터를 생성했습니다.
  GetARock/.swiftlint.yml
  GetARock/GetARock.xcodeproj/project.pbxproj
  GetARock/GetARock/Global/Literals/StringLiteral.swift
  GetARock/GetARock/Global/Utils/Date+String.swift
  GetARock/GetARock/Network/Mock/Data/MockBandData.swift
Labels: 🎸 스누피, Add

#63 [Design] 연령대 영역을 Label로 구현했습니다.
  GetARock/GetARock/Global/Resource/Storyboards/BandInfo.storyboard
  GetARock/GetARock/Screen/BandInfo/VC/BandInfoViewController.swift
Labels: 🎸 이브, Design

#57 [Design] 모여락(이벤트)의 정보 화면의 UI 를 구성합니다.
  GetARock/GetARock.xcodeproj/project.pbxproj
  GetARock/GetARock/Global/Resource/Assets.xcassets/GatheringLocatonIcon.imageset/Contents.json
  GetARock/GetARock/Global/Resource/Assets.xcassets/GatheringLocatonIcon.imageset/Group 284.png
  GetARock/GetARock/Global/Resource/Storyboards/GatheringInfoPage.storyboard
  GetARock/GetARock/Global/Resource/Storyboards/MyPage.storyboard
  GetARock/GetARock/Screen/GatheringInfo/GatheringInfoViewController.swift
Labels: 🎸 시로, Design

#65 [Design] 방명록, 이벤트 상세에 사용되는 댓글(방명록)목록, Empty VIew, 댓글(방명록) 작성 버튼을 UI컴포넌트로 제작했습니다.
  GetARock/GetARock.xcodeproj/project.pbxproj
  GetARock/GetARock/Global/UIComponent/Cell/CommentTableViewCell.swift
  GetARock/GetARock/Global/UIComponent/CommentCreateButton.swift
  GetARock/GetARock/Global/UIComponent/CommentListView.swift
  GetARock/GetARock/Global/UIComponent/EmptyListView.swift
Labels: 🎸 노엘, Design

#79 [Design] 밴드상세의 타임라인 화면 UI를 구현합니다.
  GetARock/GetARock.xcodeproj/project.pbxproj
  GetARock/GetARock/Global/Resource/Assets.xcassets/TimelineDot.imageset/Contents.json
  GetARock/GetARock/Global/Resource/Assets.xcassets/TimelineDot.imageset/TimelineDot.svg
  GetARock/GetARock/Global/Resource/Storyboards/BandTimeline.storyboard
  GetARock/GetARock/Global/Resource/Storyboards/GatheringView.storyboard
  GetARock/GetARock/Global/Resource/Xibs/BandTimelineCell.xib
  GetARock/GetARock/Screen/BandInfo/Cell/BandTimelineCell.swift
  GetARock/GetARock/Screen/BandInfo/VC/BandTimelineViewController.swift
Labels: 🎸 태니, Design, 밴드 상세

#75 [Feat] 사용자의 현재 위치를 가져와 지도 뷰에 표시합니다.
  GetARock/GetARock.xcodeproj/project.pbxproj
  GetARock/GetARock/Global/Resource/Storyboards/MainMap.storyboard
  GetARock/GetARock/Screen/MainMap/MainMapViewController.swift
Labels: 🎸 알로라, Feat, 지도

#77 [Feat] 모여락(밴드 이벤트) 추가 화면의 인터랙션(텍스트필드, 텍스트뷰, 화면 이동)을 설정합니다.
  GetARock/GetARock/Global/Resource/Storyboards/AddGathering.storyboard
  GetARock/GetARock/Screen/AddGathering/AddGatheringViewController.swift
Labels: 🎸 유니스, Feat, 모여락 추가

#90 [Fix] GatheringComment Model을 변경했습니다.
  GetARock/GetARock/Network/Mock/Data/MockBandData.swift
  GetARock/GetARock/Network/Model/GatheringComment.swift
Labels: 🎸 스누피, Fix, !HOTFIX

#85 [Design] 밴드 소개 영역을 Label로 구현했습니다.
  GetARock/GetARock/Global/Resource/Storyboards/BandInfo.storyboard
  GetARock/GetARock/Screen/BandInfo/VC/BandInfoViewController.swift
Labels: 🎸 이브, Design

#83 [Design] 댓글 작성 Custom Popup창 제작했습니다.
  GetARock/GetARock.xcodeproj/project.pbxproj
  GetARock/GetARock/Global/UIComponent/CommentCreateButton.swift
  GetARock/GetARock/Global/UIComponent/CommentWritingPopupViewController.swift
Labels: 🎸 노엘, Design

#87 [Design] 합주곡 영역을 Table View로 구현했습니다.
  GetARock/GetARock.xcodeproj/project.pbxproj
  GetARock/GetARock/Global/Resource/Storyboards/BandInfo.storyboard
  GetARock/GetARock/Global/Resource/Xibs/RepertoireTableViewCell.xib
  GetARock/GetARock/Screen/BandInfo/Cell/RepertoireTableViewCell.swift
  GetARock/GetARock/Screen/BandInfo/VC/BandInfoViewController.swift
Labels: 🎸 이브, Design
