Repository DeveloperAcademy-POSTECH/MacC-GetARock, pull requests merged in 2022-12, with the labels that each got.

#96 [Add] 지도 뷰에 더미 데이터의 밴드, 이벤트 위치를 보여줍니다.
  GetARock/GetARock.xcodeproj/project.pbxproj
  GetARock/GetARock/Screen/MainMap/Component/AnnotationView.swift
  GetARock/GetARock/Screen/MainMap/MainMapViewController.swift
Labels: 🎸 알로라, Add, 지도

#100 [Design] 기존 CommentListView에 작성하기 버튼을 추가했습니다.
  GetARock/GetARock.xcodeproj/project.pbxproj
  GetARock/GetARock/Global/UIComponent/Cell/CommentTableViewCell.swift
  GetARock/GetARock/Global/UIComponent/CommentListView.swift
  GetARock/GetARock/Screen/BandInfo/VC/VisitorCommentViewController.swift
Labels: 🎸 노엘, Design

#93 [Feat] 신고 / 삭제를 위한 기능을 구현합니다.
  GetARock/GetARock.xcodeproj/project.pbxproj
  GetARock/GetARock/Global/Resource/Storyboards/GatheringInfoPage.storyboard
  GetARock/GetARock/Global/Resource/Storyboards/GatheringView.storyboard
  GetARock/GetARock/Global/Resource/Storyboards/ReportReasonList.storyboard
  GetARock/GetARock/Global/Resource/Storyboards/ReportReasonListCell.xib
  GetARock/GetARock/Global/Resource/Xibs/ReportReasonListCell.xib
  GetARock/GetARock/Global/Resource/Xibs/ReportReasonListHeader.xib
  GetARock/GetARock/Global/UIComponent/ActionSheet.swift
  GetARock/GetARock/Screen/Gathering/GatheringCell.swift
  GetARock/GetARock/Screen/GatheringInfo/GatheringInfoViewController.swift
  GetARock/GetARock/Screen/GatheringInfo/ReportReasonListCell.swift
  GetARock/GetARock/Screen/GatheringInfo/ReportReasonListController.swift
Labels: 🎸 시로, Feat

#102 [Add] 지도 뷰에서 현재 위치를 텍스트로 보여줍니다.
  GetARock/GetARock/Global/Resource/Storyboards/MainMap.storyboard
  GetARock/GetARock/Screen/MainMap/Component/AnnotationView.swift
  GetARock/GetARock/Screen/MainMap/MainMapViewController.swift
Labels: 🎸 알로라, Add, 지도

#95 [Feat] 모여락 추가 뷰에서 완료를 눌렀을 때 모여락을 목데이터에 추가합니다.
  GetARock/GetARock/Global/Resource/Storyboards/AddGathering.storyboard
  GetARock/GetARock/Screen/AddGathering/AddGatheringViewController.swift
Labels: 🎸 유니스, Feat, 모여락 추가

#110 [Feat] 내모여락 리스트에 항목들을 목데이터에서 불러올 수 있도록 인터페이스를 만들었습니다.
  GetARock/GetARock.xcodeproj/project.pbxproj
  GetARock/GetARock/Global/Resource/Storyboards/GatheringList.storyboard
  GetARock/GetARock/Global/Resource/Xibs/GatheringListCell.xib
  GetARock/GetARock/Screen/Gathering/GatheringCreatedViewController.swift
  GetARock/GetARock/Screen/Gathering/GatheringListCell.swift
  GetARock/GetARock/Screen/Gathering/GatheringListViewController.swift
Labels: 🎸 태니, Feat, 내 모여락

#111 [Feat] 밴드 타임라인에 항목들을 목데이터에서 불러올 수 있도록 인터페이스를 만들었습니다.
  GetARock/GetARock/Global/Resource/Storyboards/BandTimeline.storyboard
  GetARock/GetARock/Global/Resource/Xibs/BandTimelineCell.xib
  GetARock/GetARock/Screen/BandInfo/Cell/BandTimelineCell.swift
  GetARock/GetARock/Screen/BandInfo/VC/BandTimelineViewController.swift
Labels: 🎸 태니, Feat, 밴드 상세
