Repository DeveloperAcademy-POSTECH/MacC-GetARock, pull requests merged in 2023-01, with the labels that each got.

#117 [Design] 모여락 장소 입력 뷰의 UI를 구현합니다.
  GetARock/GetARock.xcodeproj/project.pbxproj
  GetARock/GetARock/Global/Resource/Storyboards/AddGathering.storyboard
  GetARock/GetARock/Global/Resource/Xibs/LocationCandidateCell.xib
  GetARock/GetARock/Screen/AddGathering/AddGatheringLocationViewController.swift
  GetARock/GetARock/Screen/AddGathering/AddGatheringViewController.swift
  GetARock/GetARock/Screen/AddGathering/LocationCandidateCell.swift
  GetARock/GetARock/Screen/AddGathering/LocationSelectViewController.swift
Labels: 🎸 유니스, Design, 모여락 추가

#114 [Feat] 댓글(방명록) 팝업에서 글자 작성 후 추가하기 버튼 선택 시 해당 댓글이 목록에 추가됩니다.
  GetARock/GetARock/Global/UIComponent/CommentListView.swift
  GetARock/GetARock/Global/UIComponent/CommentWritingPopupViewController.swift
  GetARock/GetARock/Screen/BandInfo/VC/VisitorCommentViewController.swift
Labels: 🎸 노엘, Feat

#92 [Feat] 내모여락 화면에서 SegmentedControl 버튼을 누르면 해당하는 화면이 나타납니다.
  GetARock/GetARock.xcodeproj/project.pbxproj
  GetARock/GetARock/Global/Resource/Storyboards/GatheringList.storyboard
  GetARock/GetARock/Global/UIComponent/SwitchingViewSegmentedControl.swift
  GetARock/GetARock/Screen/Gathering/GatheringListTapViewController.swift
Labels: 🎸 머피, Feat, 내 모여락

#118 [Setting] Firebase 개발환경 세팅
  GetARock/GetARock.xcodeproj/project.pbxproj
  GetARock/GetARock.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  GetARock/GetARock/Global/Supports/AppDelegate.swift
  GetARock/GetARock/GoogleService-Info.plist
Labels: 🎸 스누피, Setting

#109 [Design] 더미 데이터를 밴드 정보 View에 연결했습니다.
  GetARock/GetARock.xcodeproj/project.pbxproj
  GetARock/GetARock/Global/Extension/UIView+Extension.swift
  GetARock/GetARock/Global/Resource/Assets.xcassets/Bass.imageset/Bass.png
  GetARock/GetARock/Global/Resource/Assets.xcassets/Bass.imageset/Contents.json
  GetARock/GetARock/Global/Resource/Assets.xcassets/Drum.imageset/Contents.json
  GetARock/GetARock/Global/Resource/Assets.xcassets/Drum.imageset/Drum.png
  GetARock/GetARock/Global/Resource/Assets.xcassets/Etc.imageset/Contents.json
  GetARock/GetARock/Global/Resource/Assets.xcassets/Etc.imageset/Etc.png
  GetARock/GetARock/Global/Resource/Assets.xcassets/Guitar.imageset/Contents.json
  GetARock/GetARock/Global/Resource/Assets.xcassets/Guitar.imageset/Guitar.png
  GetARock/GetARock/Global/Resource/Assets.xcassets/Keyboard.imageset/Contents.json
  GetARock/GetARock/Global/Resource/Assets.xcassets/Keyboard.imageset/Keyboard.png
  GetARock/GetARock/Global/Resource/Assets.xcassets/Vocal.imageset/Contents.json
  GetARock/GetARock/Global/Resource/Assets.xcassets/Vocal.imageset/Vocal.png
  GetARock/GetARock/Global/Resource/Storyboards/BandInfo.storyboard
  GetARock/GetARock/Network/Model/PlayPosition.swift
  GetARock/GetARock/Screen/BandInfo/Cell/BandMemberCollectionViewCell.swift
  GetARock/GetARock/Screen/BandInfo/Cell/RepertoireTableViewCell.swift
  GetARock/GetARock/Screen/BandInfo/VC/BandInfoViewController.swift
Labels: 🎸 이브, Add

#131 [Feat] 방명록의 ellipsis 버튼을 누르면 ActionSheet를 띄우고 셀 삭제까지 할 수 있도록 기능을 추가했습니다.
  GetARock/GetARock/Global/UIComponent/Cell/CommentTableViewCell.swift
  GetARock/GetARock/Global/UIComponent/CommentListView.swift
  GetARock/GetARock/Screen/BandInfo/VC/VisitorCommentViewController.swift
Labels: 🎸 노엘, Feat

#122 [Feat] 모여락 추가의 장소 검색을 구현합니다.
  GetARock/GetARock.xcodeproj/project.pbxproj
  GetARock/GetARock/Global/Resource/Storyboards/AddGathering.storyboard
  GetARock/GetARock/Global/Resource/Xibs/LocationCandidateCell.xib
  GetARock/GetARock/Screen/AddGathering/AddGatheringLocationViewController.swift
  GetARock/GetARock/Screen/AddGathering/LocationSearchResultViewController.swift
  GetARock/GetARock/Screen/AddGathering/LocationSearchViewController.swift
  GetARock/GetARock/Screen/AddGathering/LocationSelectViewController.swift
Labels: 🎸 유니스, Feat, 모여락 추가

#130 [Design] 지도 뷰의 게더링 핀을 커스텀 이미지로 변경합니다.
  GetARock/GetARock.xcodeproj/project.pbxproj
  GetARock/GetARock/Screen/MainMap/Component/AnnotationView.swift
  GetARock/GetARock/Screen/MainMap/Component/BandAnnotationView.swift
  GetARock/GetARock/Screen/MainMap/Component/GatheringAnnotationView.swift
  GetARock/GetARock/Screen/MainMap/MainMapViewController.swift
Labels: 🎸 알로라, Design, 지도

#123 [Feat] 검색한 장소를 모여락 추가 화면에서 모여락 위치로 저장합니다.
  GetARock/GetARock.xcodeproj/project.pbxproj
  GetARock/GetARock/Global/Resource/Storyboards/AddGathering.storyboard
  GetARock/GetARock/Screen/AddGathering/Cell/LocationCandidateCell.swift
  GetARock/GetARock/Screen/AddGathering/VC/AddGatheringViewController.swift
  GetARock/GetARock/Screen/AddGathering/VC/Extension/AddGatheringViewController+ScrollAdaptToKeyboard.swift
  GetARock/GetARock/Screen/AddGathering/VC/Extension/LocationSearchResultViewController+ScrollAdaptToKeyboard.swift
  GetARock/GetARock/Screen/AddGathering/VC/LocationSearchResultViewController.swift
  GetARock/GetARock/Screen/AddGathering/VC/LocationSearchViewController.swift
Labels: 🎸 유니스, Feat, 모여락 추가

#136 [Feat] 모여락 상세페이지와 댓글 뷰를 연결했습니다.
  GetARock/GetARock/Global/Resource/Storyboards/GatheringInfoPage.storyboard
  GetARock/GetARock/Global/UIComponent/CommentWritingPopupViewController.swift
  GetARock/GetARock/Screen/GatheringInfo/GatheringInfoViewController.swift
Labels: 🎸 시로, Feat

#133 [Feat] Firebase를 이용한 API를 구현했습니다.
  GetARock/GetARock.xcodeproj/project.pbxproj
  GetARock/GetARock/Global/Extension/CollectionReference+Extension.swift
  GetARock/GetARock/Global/Extension/Encodable+Extension.swift
  GetARock/GetARock/Network/API/AuthAPI.swift
  GetARock/GetARock/Network/API/BandAPI.swift
  GetARock/GetARock/Network/API/GatheringAPI.swift
  GetARock/GetARock/Network/Model/AgeGroup.swift
  GetARock/GetARock/Network/Model/Band.swift
  GetARock/GetARock/Network/Model/Coordinate.swift
  GetARock/GetARock/Network/Model/DTO/GatheringCommentDTO.swift
  GetARock/GetARock/Network/Model/DTO/GatheringDTO.swift
  GetARock/GetARock/Network/Model/DTO/VisitorCommentDTO.swift
  GetARock/GetARock/Network/Model/Gathering.swift
  GetARock/GetARock/Network/Model/Location.swift
  GetARock/GetARock/Network/Model/PlayPosition.swift
  GetARock/GetARock/Network/Storage/UserDefaultHandler.swift
  GetARock/GetARock/Network/Storage/UserDefaultStorage.swift
Labels: 🎸 스누피, Feat

#134 [Fix] 문제 요인인 "주변 검색"을 장소 검색 결과에서 제외하는 겸 대한민국으로 검색결과를 제한합니다.
  GetARock/GetARock/Screen/AddGathering/VC/Extension/LocationSearchResultViewController+ScrollAdaptToKeyboard.swift
  GetARock/GetARock/Screen/AddGathering/VC/LocationSearchResultViewController.swift
  GetARock/GetARock/Screen/AddGathering/VC/LocationSearchViewController.swift
Labels: 🎸 유니스, Fix, 모여락 추가
